DROP TABLE IF EXISTS NEVENT;

-- h2 syntax
CREATE TABLE IF NOT EXISTS NEVENT(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_ID VARCHAR NOT NULL,
  SOURCE VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  DESCRIPTION VARCHAR,
  START_TIME VARCHAR NOT NULL,
  END_TIME VARCHAR NOT NULL,
  LOCATION_NAME VARCHAR,
  COUNTRY VARCHAR,
  REGION VARCHAR,
  LOCALITY VARCHAR,
  STREET_ADDRESS VARCHAR,
  LONGITUDE REAL,
  LATITUDE REAL,
  ORGANIZER VARCHAR,
  URL VARCHAR,
  VIRTUAL INTEGER,
  LAST_UPDATE VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL
);

-- sqlite3 syntax
/*
          CREATE TABLE IF NOT EXISTS EVENT(
            ID INT PRIMARY KEY AUTOINCREMENT,
            EVENT_ID TEXT NOT NULL,
            SOURCE STRING NOT NULL,
            NAME TEXT NOT NULL,
            DESCRIPTION TEXT,
            START_TIME TEXT NOT NULL,
            END_TIME TEXT NOT NULL,
            LOCATION_NAME TEXT,
            COUNTRY TEXT,
            REGION TEXT,
            LOCALITY TEXT,
            STREET_ADDRESS TEXT,
            LONGITUDE REAL,
            LATITUDE REAL,
            ORGANIZER TEXT,
            URL TEXT,
            VIRTUAL INTEGER,
            LAST_UPDATE TEXT NOT NULL,
            STATUS TEXT NOT NULL
          );
*/

