-- sqlite3
CREATE TABLE IF NOT EXISTS EVENTBRITE_EVENT(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_ID TEXT NOT NULL,
  JSON TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENT(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_ID TEXT NOT NULL,
  SOURCE TEXT,
  NAME TEXT,
  DESCRIPTION TEXT,
  START_TIME INT,
  END_TIME INT ,
  -- embedded
  LOCATION_NAME TEXT,
  COUNTRY TEXT,
  REGION TEXT,
  LOCALITY TEXT,
  STREET_ADDRESS TEXT,
  LONGITUDE REAL,
  LATITUDE REAL,
  -- -------
  ORGANIZER TEXT,
  URL TEXT,
  VIRTUAL TEXT, --sqlite3 doesn't have a boolean type
  LAST_UPDATE INT,
  STATUS TEXT
);

-- h2
/*
CREATE TABLE EVENTBRITE_EVENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  EVENT_ID VARCHAR NOT NULL,
  JSON VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  EVENT_ID VARCHAR NOT NULL,
  SOURCE VARCHAR,
  NAME VARCHAR,
  DESCRIPTION VARCHAR,
  START_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  -- embedded
  LOCATION_NAME VARCHAR,
  COUNTRY VARCHAR,
  REGION VARCHAR,
  LOCALITY VARCHAR,
  STREET_ADDRESS VARCHAR,
  LONGITUDE REAL,
  LATITUDE REAL,
  ORGANIZER VARCHAR,
  URL VARCHAR,
  -- VIRTUAL INTEGER, -- h2 has a boolean type and the dialect mapping uses it
  VIRTUAL BOOLEAN,
  LAST_UPDATE TIMESTAMP,
  STATUS VARCHAR
);
*/


