-- h2
CREATE TABLE EVENTBRITE_EVENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  EVENT_ID VARCHAR NOT NULL,
  JSON VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  EVENT_ID VARCHAR NOT NULL,
  SOURCE VARCHAR,
  NAME VARCHAR,
  DESCRIPTION VARCHAR,
  START_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  -- embedded
  LOCATION_NAME VARCHAR,
  COUNTRY VARCHAR,
  REGION VARCHAR,
  LOCALITY VARCHAR,
  STREET_ADDRESS VARCHAR,
  LONGITUDE REAL,
  LATITUDE REAL,
  ORGANIZER VARCHAR,
  URL VARCHAR,
  -- VIRTUAL INTEGER, -- h2 has a boolean type and the dialect mapping uses it
  VIRTUAL BOOLEAN,
  LAST_UPDATE TIMESTAMP,
  STATUS VARCHAR
);

